/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBurnReserveDeposit } from "./IBurnReserveDeposit";
export type { RevenueRouter } from "./RevenueRouter";
