/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface RevenueRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOM"
      | "BURN_RESERVE_BPS"
      | "burnReserve"
      | "operator"
      | "registry"
      | "submitRevenue"
      | "totalRevenueSubmitted"
      | "usdc"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RevenueSubmitted"): EventFragment;

  encodeFunctionData(functionFragment: "BPS_DENOM", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "BURN_RESERVE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "burnReserve",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitRevenue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRevenueSubmitted",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(functionFragment: "BPS_DENOM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BURN_RESERVE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRevenueSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace RevenueSubmittedEvent {
  export type InputTuple = [
    operator: AddressLike,
    gross: BigNumberish,
    burnReserveShare: BigNumberish,
    operatorShare: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    gross: bigint,
    burnReserveShare: bigint,
    operatorShare: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    operator: string;
    gross: bigint;
    burnReserveShare: bigint;
    operatorShare: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RevenueRouter extends BaseContract {
  connect(runner?: ContractRunner | null): RevenueRouter;
  waitForDeployment(): Promise<this>;

  interface: RevenueRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOM: TypedContractMethod<[], [bigint], "view">;

  BURN_RESERVE_BPS: TypedContractMethod<[], [bigint], "view">;

  burnReserve: TypedContractMethod<[], [string], "view">;

  operator: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  submitRevenue: TypedContractMethod<
    [grossAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalRevenueSubmitted: TypedContractMethod<[], [bigint], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BURN_RESERVE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "burnReserve"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitRevenue"
  ): TypedContractMethod<[grossAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalRevenueSubmitted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "RevenueSubmitted"
  ): TypedContractEvent<
    RevenueSubmittedEvent.InputTuple,
    RevenueSubmittedEvent.OutputTuple,
    RevenueSubmittedEvent.OutputObject
  >;

  filters: {
    "RevenueSubmitted(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RevenueSubmittedEvent.InputTuple,
      RevenueSubmittedEvent.OutputTuple,
      RevenueSubmittedEvent.OutputObject
    >;
    RevenueSubmitted: TypedContractEvent<
      RevenueSubmittedEvent.InputTuple,
      RevenueSubmittedEvent.OutputTuple,
      RevenueSubmittedEvent.OutputObject
    >;
  };
}
