/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBurnReserveDeposit,
  IBurnReserveDepositInterface,
} from "../../../../contracts/project/RevenueRouter.sol/IBurnReserveDeposit";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "depositReserve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBurnReserveDeposit__factory {
  static readonly abi = _abi;
  static createInterface(): IBurnReserveDepositInterface {
    return new Interface(_abi) as IBurnReserveDepositInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBurnReserveDeposit {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBurnReserveDeposit;
  }
}
