/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface BurnReserveInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOM"
      | "BURN_PAYOUT_BPS"
      | "burn"
      | "burnPayout"
      | "depositReserve"
      | "factory"
      | "icoPricePerToken"
      | "operator"
      | "registry"
      | "reserveBalance"
      | "revenueRouter"
      | "sale"
      | "setIcoPrice"
      | "setRevenueRouter"
      | "setSale"
      | "token"
      | "totalBurned"
      | "totalReserve"
      | "usdc"
      | "wireToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IcoPriceSet"
      | "ReserveDeposited"
      | "TokenWired"
      | "TokensBurned"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BPS_DENOM", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "BURN_PAYOUT_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "burn", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "burnPayout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositReserve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "icoPricePerToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reserveBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revenueRouter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sale", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setIcoPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRevenueRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSale",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalBurned",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalReserve",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "wireToken",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "BPS_DENOM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BURN_PAYOUT_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burnPayout", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "icoPricePerToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reserveBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revenueRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setIcoPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRevenueRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSale", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalBurned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wireToken", data: BytesLike): Result;
}

export namespace IcoPriceSetEvent {
  export type InputTuple = [price: BigNumberish];
  export type OutputTuple = [price: bigint];
  export interface OutputObject {
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveDepositedEvent {
  export type InputTuple = [amount: BigNumberish, newTotal: BigNumberish];
  export type OutputTuple = [amount: bigint, newTotal: bigint];
  export interface OutputObject {
    amount: bigint;
    newTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWiredEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensBurnedEvent {
  export type InputTuple = [
    burner: AddressLike,
    tokenAmount: BigNumberish,
    usdcPayout: BigNumberish
  ];
  export type OutputTuple = [
    burner: string,
    tokenAmount: bigint,
    usdcPayout: bigint
  ];
  export interface OutputObject {
    burner: string;
    tokenAmount: bigint;
    usdcPayout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BurnReserve extends BaseContract {
  connect(runner?: ContractRunner | null): BurnReserve;
  waitForDeployment(): Promise<this>;

  interface: BurnReserveInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOM: TypedContractMethod<[], [bigint], "view">;

  BURN_PAYOUT_BPS: TypedContractMethod<[], [bigint], "view">;

  burn: TypedContractMethod<[tokenAmount: BigNumberish], [void], "nonpayable">;

  burnPayout: TypedContractMethod<
    [tokenAmount: BigNumberish],
    [bigint],
    "view"
  >;

  depositReserve: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  factory: TypedContractMethod<[], [string], "view">;

  icoPricePerToken: TypedContractMethod<[], [bigint], "view">;

  operator: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  reserveBalance: TypedContractMethod<[], [bigint], "view">;

  revenueRouter: TypedContractMethod<[], [string], "view">;

  sale: TypedContractMethod<[], [string], "view">;

  setIcoPrice: TypedContractMethod<[price: BigNumberish], [void], "nonpayable">;

  setRevenueRouter: TypedContractMethod<
    [_router: AddressLike],
    [void],
    "nonpayable"
  >;

  setSale: TypedContractMethod<[_sale: AddressLike], [void], "nonpayable">;

  token: TypedContractMethod<[], [string], "view">;

  totalBurned: TypedContractMethod<[], [bigint], "view">;

  totalReserve: TypedContractMethod<[], [bigint], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  wireToken: TypedContractMethod<[token_: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BURN_PAYOUT_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<[tokenAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "burnPayout"
  ): TypedContractMethod<[tokenAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositReserve"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "icoPricePerToken"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reserveBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revenueRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sale"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setIcoPrice"
  ): TypedContractMethod<[price: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRevenueRouter"
  ): TypedContractMethod<[_router: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSale"
  ): TypedContractMethod<[_sale: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalBurned"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "wireToken"
  ): TypedContractMethod<[token_: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "IcoPriceSet"
  ): TypedContractEvent<
    IcoPriceSetEvent.InputTuple,
    IcoPriceSetEvent.OutputTuple,
    IcoPriceSetEvent.OutputObject
  >;
  getEvent(
    key: "ReserveDeposited"
  ): TypedContractEvent<
    ReserveDepositedEvent.InputTuple,
    ReserveDepositedEvent.OutputTuple,
    ReserveDepositedEvent.OutputObject
  >;
  getEvent(
    key: "TokenWired"
  ): TypedContractEvent<
    TokenWiredEvent.InputTuple,
    TokenWiredEvent.OutputTuple,
    TokenWiredEvent.OutputObject
  >;
  getEvent(
    key: "TokensBurned"
  ): TypedContractEvent<
    TokensBurnedEvent.InputTuple,
    TokensBurnedEvent.OutputTuple,
    TokensBurnedEvent.OutputObject
  >;

  filters: {
    "IcoPriceSet(uint256)": TypedContractEvent<
      IcoPriceSetEvent.InputTuple,
      IcoPriceSetEvent.OutputTuple,
      IcoPriceSetEvent.OutputObject
    >;
    IcoPriceSet: TypedContractEvent<
      IcoPriceSetEvent.InputTuple,
      IcoPriceSetEvent.OutputTuple,
      IcoPriceSetEvent.OutputObject
    >;

    "ReserveDeposited(uint256,uint256)": TypedContractEvent<
      ReserveDepositedEvent.InputTuple,
      ReserveDepositedEvent.OutputTuple,
      ReserveDepositedEvent.OutputObject
    >;
    ReserveDeposited: TypedContractEvent<
      ReserveDepositedEvent.InputTuple,
      ReserveDepositedEvent.OutputTuple,
      ReserveDepositedEvent.OutputObject
    >;

    "TokenWired(address)": TypedContractEvent<
      TokenWiredEvent.InputTuple,
      TokenWiredEvent.OutputTuple,
      TokenWiredEvent.OutputObject
    >;
    TokenWired: TypedContractEvent<
      TokenWiredEvent.InputTuple,
      TokenWiredEvent.OutputTuple,
      TokenWiredEvent.OutputObject
    >;

    "TokensBurned(address,uint256,uint256)": TypedContractEvent<
      TokensBurnedEvent.InputTuple,
      TokensBurnedEvent.OutputTuple,
      TokensBurnedEvent.OutputObject
    >;
    TokensBurned: TypedContractEvent<
      TokensBurnedEvent.InputTuple,
      TokensBurnedEvent.OutputTuple,
      TokensBurnedEvent.OutputObject
    >;
  };
}
