/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BurnReserve } from "./BurnReserve";
export type { IRWATokenBurnFrom } from "./IRWATokenBurnFrom";
