/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "banList"
      | "factory"
      | "getAllOperators"
      | "getProjectContracts"
      | "isApprovedProject"
      | "isBanned"
      | "isProjectOperator"
      | "projectBurnReserve"
      | "projectRevenueRouter"
      | "projectSale"
      | "projectStaking"
      | "projectToken"
      | "protocolTreasury"
      | "registerProjectContracts"
      | "requireAdmin"
      | "requireApprovedProject"
      | "requireNotBanned"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "banList", values?: undefined): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllOperators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectContracts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedProject",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBanned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProjectOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projectBurnReserve",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projectRevenueRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projectSale",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projectStaking",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projectToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerProjectContracts",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requireAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requireApprovedProject",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requireNotBanned",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "banList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isBanned", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isProjectOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectBurnReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectRevenueRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectStaking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProjectContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireApprovedProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireNotBanned",
    data: BytesLike
  ): Result;
}

export interface IRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IRegistry;
  waitForDeployment(): Promise<this>;

  interface: IRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  banList: TypedContractMethod<[], [string], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  getAllOperators: TypedContractMethod<[], [string[]], "view">;

  getProjectContracts: TypedContractMethod<
    [operator: AddressLike],
    [
      [string, string, string, string, string] & {
        token: string;
        sale: string;
        staking: string;
        burnReserve: string;
        revenueRouter: string;
      }
    ],
    "view"
  >;

  isApprovedProject: TypedContractMethod<
    [operator: AddressLike],
    [boolean],
    "view"
  >;

  isBanned: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  isProjectOperator: TypedContractMethod<
    [addr: AddressLike],
    [boolean],
    "view"
  >;

  projectBurnReserve: TypedContractMethod<
    [operator: AddressLike],
    [string],
    "view"
  >;

  projectRevenueRouter: TypedContractMethod<
    [operator: AddressLike],
    [string],
    "view"
  >;

  projectSale: TypedContractMethod<[operator: AddressLike], [string], "view">;

  projectStaking: TypedContractMethod<
    [operator: AddressLike],
    [string],
    "view"
  >;

  projectToken: TypedContractMethod<[operator: AddressLike], [string], "view">;

  protocolTreasury: TypedContractMethod<[], [string], "view">;

  registerProjectContracts: TypedContractMethod<
    [
      operator: AddressLike,
      token: AddressLike,
      sale: AddressLike,
      staking: AddressLike,
      burnReserve: AddressLike,
      revenueRouter: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  requireAdmin: TypedContractMethod<[addr: AddressLike], [void], "view">;

  requireApprovedProject: TypedContractMethod<
    [addr: AddressLike],
    [void],
    "view"
  >;

  requireNotBanned: TypedContractMethod<[addr: AddressLike], [void], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "banList"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllOperators"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProjectContracts"
  ): TypedContractMethod<
    [operator: AddressLike],
    [
      [string, string, string, string, string] & {
        token: string;
        sale: string;
        staking: string;
        burnReserve: string;
        revenueRouter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedProject"
  ): TypedContractMethod<[operator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isBanned"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProjectOperator"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "projectBurnReserve"
  ): TypedContractMethod<[operator: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "projectRevenueRouter"
  ): TypedContractMethod<[operator: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "projectSale"
  ): TypedContractMethod<[operator: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "projectStaking"
  ): TypedContractMethod<[operator: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "projectToken"
  ): TypedContractMethod<[operator: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "protocolTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerProjectContracts"
  ): TypedContractMethod<
    [
      operator: AddressLike,
      token: AddressLike,
      sale: AddressLike,
      staking: AddressLike,
      burnReserve: AddressLike,
      revenueRouter: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requireAdmin"
  ): TypedContractMethod<[addr: AddressLike], [void], "view">;
  getFunction(
    nameOrSignature: "requireApprovedProject"
  ): TypedContractMethod<[addr: AddressLike], [void], "view">;
  getFunction(
    nameOrSignature: "requireNotBanned"
  ): TypedContractMethod<[addr: AddressLike], [void], "view">;

  filters: {};
}
