/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BurnReserve__factory } from "./BurnReserve__factory";
export { IRWATokenBurnFrom__factory } from "./IRWATokenBurnFrom__factory";
