/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRWATokenBurnFrom,
  IRWATokenBurnFromInterface,
} from "../../../../contracts/project/BurnReserve.sol/IRWATokenBurnFrom";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burnFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRWATokenBurnFrom__factory {
  static readonly abi = _abi;
  static createInterface(): IRWATokenBurnFromInterface {
    return new Interface(_abi) as IRWATokenBurnFromInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRWATokenBurnFrom {
    return new Contract(address, _abi, runner) as unknown as IRWATokenBurnFrom;
  }
}
