/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ProjectFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "deployProject" | "registry" | "usdc"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProjectDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "deployProject",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "deployProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace ProjectDeployedEvent {
  export type InputTuple = [
    operator: AddressLike,
    token: AddressLike,
    sale: AddressLike,
    staking: AddressLike,
    burnReserve: AddressLike,
    revenueRouter: AddressLike
  ];
  export type OutputTuple = [
    operator: string,
    token: string,
    sale: string,
    staking: string,
    burnReserve: string,
    revenueRouter: string
  ];
  export interface OutputObject {
    operator: string;
    token: string;
    sale: string;
    staking: string;
    burnReserve: string;
    revenueRouter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProjectFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ProjectFactory;
  waitForDeployment(): Promise<this>;

  interface: ProjectFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployProject: TypedContractMethod<
    [
      tokenName: string,
      tokenSymbol: string,
      totalSupply: BigNumberish,
      salePricePerToken: BigNumberish,
      saleDeadline: BigNumberish
    ],
    [
      [string, string, string, string, string] & {
        tokenAddr: string;
        saleAddr: string;
        stakingAddr: string;
        burnReserveAddr: string;
        revenueRouterAddr: string;
      }
    ],
    "nonpayable"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployProject"
  ): TypedContractMethod<
    [
      tokenName: string,
      tokenSymbol: string,
      totalSupply: BigNumberish,
      salePricePerToken: BigNumberish,
      saleDeadline: BigNumberish
    ],
    [
      [string, string, string, string, string] & {
        tokenAddr: string;
        saleAddr: string;
        stakingAddr: string;
        burnReserveAddr: string;
        revenueRouterAddr: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ProjectDeployed"
  ): TypedContractEvent<
    ProjectDeployedEvent.InputTuple,
    ProjectDeployedEvent.OutputTuple,
    ProjectDeployedEvent.OutputObject
  >;

  filters: {
    "ProjectDeployed(address,address,address,address,address,address)": TypedContractEvent<
      ProjectDeployedEvent.InputTuple,
      ProjectDeployedEvent.OutputTuple,
      ProjectDeployedEvent.OutputObject
    >;
    ProjectDeployed: TypedContractEvent<
      ProjectDeployedEvent.InputTuple,
      ProjectDeployedEvent.OutputTuple,
      ProjectDeployedEvent.OutputObject
    >;
  };
}
