/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RWARegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptAdminTransfer"
      | "admin"
      | "approveProject"
      | "banAddress"
      | "banList"
      | "bulkBan"
      | "bulkUnban"
      | "factory"
      | "getAllOperators"
      | "getProjectContracts"
      | "getProjectName"
      | "initiateAdminTransfer"
      | "isApprovedProject"
      | "isBanned"
      | "isProjectActive"
      | "isProjectOperator"
      | "pendingAdmin"
      | "projectBurnReserve"
      | "projectRevenueRouter"
      | "projectSale"
      | "projectStaking"
      | "projectToken"
      | "protocolTreasury"
      | "registerProjectContracts"
      | "requireAdmin"
      | "requireApprovedProject"
      | "requireNotBanned"
      | "revokeProject"
      | "setBanList"
      | "setFactory"
      | "setTreasury"
      | "unbanAddress"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressBanned"
      | "AddressUnbanned"
      | "AdminTransferCompleted"
      | "AdminTransferInitiated"
      | "BanListSet"
      | "BulkBanned"
      | "FactorySet"
      | "ProjectApproved"
      | "ProjectContractsRegistered"
      | "ProjectRevoked"
      | "TreasurySet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptAdminTransfer",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approveProject",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "banAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "banList", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bulkBan",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "bulkUnban",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllOperators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectContracts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectName",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateAdminTransfer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedProject",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBanned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProjectActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProjectOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projectBurnReserve",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projectRevenueRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projectSale",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projectStaking",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projectToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerProjectContracts",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requireAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requireApprovedProject",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requireNotBanned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeProject",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBanList",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unbanAddress",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptAdminTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "banAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "banList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bulkBan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bulkUnban", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateAdminTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isBanned", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isProjectActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProjectOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectBurnReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectRevenueRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectStaking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProjectContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireApprovedProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireNotBanned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBanList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFactory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unbanAddress",
    data: BytesLike
  ): Result;
}

export namespace AddressBannedEvent {
  export type InputTuple = [target: AddressLike, by: AddressLike];
  export type OutputTuple = [target: string, by: string];
  export interface OutputObject {
    target: string;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddressUnbannedEvent {
  export type InputTuple = [target: AddressLike, by: AddressLike];
  export type OutputTuple = [target: string, by: string];
  export interface OutputObject {
    target: string;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminTransferCompletedEvent {
  export type InputTuple = [newAdmin: AddressLike];
  export type OutputTuple = [newAdmin: string];
  export interface OutputObject {
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminTransferInitiatedEvent {
  export type InputTuple = [newAdmin: AddressLike];
  export type OutputTuple = [newAdmin: string];
  export interface OutputObject {
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BanListSetEvent {
  export type InputTuple = [banList: AddressLike];
  export type OutputTuple = [banList: string];
  export interface OutputObject {
    banList: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BulkBannedEvent {
  export type InputTuple = [count: BigNumberish, by: AddressLike];
  export type OutputTuple = [count: bigint, by: string];
  export interface OutputObject {
    count: bigint;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FactorySetEvent {
  export type InputTuple = [factory: AddressLike];
  export type OutputTuple = [factory: string];
  export interface OutputObject {
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectApprovedEvent {
  export type InputTuple = [operator: AddressLike, name: string];
  export type OutputTuple = [operator: string, name: string];
  export interface OutputObject {
    operator: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectContractsRegisteredEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectRevokedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasurySetEvent {
  export type InputTuple = [treasury: AddressLike];
  export type OutputTuple = [treasury: string];
  export interface OutputObject {
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RWARegistry extends BaseContract {
  connect(runner?: ContractRunner | null): RWARegistry;
  waitForDeployment(): Promise<this>;

  interface: RWARegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptAdminTransfer: TypedContractMethod<[], [void], "nonpayable">;

  admin: TypedContractMethod<[], [string], "view">;

  approveProject: TypedContractMethod<
    [operator: AddressLike, name: string],
    [void],
    "nonpayable"
  >;

  banAddress: TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  banList: TypedContractMethod<[], [string], "view">;

  bulkBan: TypedContractMethod<[targets: AddressLike[]], [void], "nonpayable">;

  bulkUnban: TypedContractMethod<
    [targets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  factory: TypedContractMethod<[], [string], "view">;

  getAllOperators: TypedContractMethod<[], [string[]], "view">;

  getProjectContracts: TypedContractMethod<
    [operator: AddressLike],
    [
      [string, string, string, string, string] & {
        token: string;
        sale: string;
        staking: string;
        burnReserve: string;
        revenueRouter: string;
      }
    ],
    "view"
  >;

  getProjectName: TypedContractMethod<
    [operator: AddressLike],
    [string],
    "view"
  >;

  initiateAdminTransfer: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  isApprovedProject: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  isBanned: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isProjectActive: TypedContractMethod<
    [operator: AddressLike],
    [boolean],
    "view"
  >;

  isProjectOperator: TypedContractMethod<
    [addr: AddressLike],
    [boolean],
    "view"
  >;

  pendingAdmin: TypedContractMethod<[], [string], "view">;

  projectBurnReserve: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  projectRevenueRouter: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  projectSale: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  projectStaking: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  projectToken: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  protocolTreasury: TypedContractMethod<[], [string], "view">;

  registerProjectContracts: TypedContractMethod<
    [
      operator: AddressLike,
      token: AddressLike,
      sale: AddressLike,
      staking: AddressLike,
      burnReserve: AddressLike,
      revenueRouter: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  requireAdmin: TypedContractMethod<[addr: AddressLike], [void], "view">;

  requireApprovedProject: TypedContractMethod<
    [addr: AddressLike],
    [void],
    "view"
  >;

  requireNotBanned: TypedContractMethod<[addr: AddressLike], [void], "view">;

  revokeProject: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  setBanList: TypedContractMethod<
    [_banList: AddressLike],
    [void],
    "nonpayable"
  >;

  setFactory: TypedContractMethod<
    [_factory: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  unbanAddress: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptAdminTransfer"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveProject"
  ): TypedContractMethod<
    [operator: AddressLike, name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "banAddress"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "banList"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bulkBan"
  ): TypedContractMethod<[targets: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bulkUnban"
  ): TypedContractMethod<[targets: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllOperators"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProjectContracts"
  ): TypedContractMethod<
    [operator: AddressLike],
    [
      [string, string, string, string, string] & {
        token: string;
        sale: string;
        staking: string;
        burnReserve: string;
        revenueRouter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProjectName"
  ): TypedContractMethod<[operator: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "initiateAdminTransfer"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isApprovedProject"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isBanned"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProjectActive"
  ): TypedContractMethod<[operator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProjectOperator"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "projectBurnReserve"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "projectRevenueRouter"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "projectSale"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "projectStaking"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "projectToken"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "protocolTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerProjectContracts"
  ): TypedContractMethod<
    [
      operator: AddressLike,
      token: AddressLike,
      sale: AddressLike,
      staking: AddressLike,
      burnReserve: AddressLike,
      revenueRouter: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requireAdmin"
  ): TypedContractMethod<[addr: AddressLike], [void], "view">;
  getFunction(
    nameOrSignature: "requireApprovedProject"
  ): TypedContractMethod<[addr: AddressLike], [void], "view">;
  getFunction(
    nameOrSignature: "requireNotBanned"
  ): TypedContractMethod<[addr: AddressLike], [void], "view">;
  getFunction(
    nameOrSignature: "revokeProject"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBanList"
  ): TypedContractMethod<[_banList: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFactory"
  ): TypedContractMethod<[_factory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unbanAddress"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AddressBanned"
  ): TypedContractEvent<
    AddressBannedEvent.InputTuple,
    AddressBannedEvent.OutputTuple,
    AddressBannedEvent.OutputObject
  >;
  getEvent(
    key: "AddressUnbanned"
  ): TypedContractEvent<
    AddressUnbannedEvent.InputTuple,
    AddressUnbannedEvent.OutputTuple,
    AddressUnbannedEvent.OutputObject
  >;
  getEvent(
    key: "AdminTransferCompleted"
  ): TypedContractEvent<
    AdminTransferCompletedEvent.InputTuple,
    AdminTransferCompletedEvent.OutputTuple,
    AdminTransferCompletedEvent.OutputObject
  >;
  getEvent(
    key: "AdminTransferInitiated"
  ): TypedContractEvent<
    AdminTransferInitiatedEvent.InputTuple,
    AdminTransferInitiatedEvent.OutputTuple,
    AdminTransferInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "BanListSet"
  ): TypedContractEvent<
    BanListSetEvent.InputTuple,
    BanListSetEvent.OutputTuple,
    BanListSetEvent.OutputObject
  >;
  getEvent(
    key: "BulkBanned"
  ): TypedContractEvent<
    BulkBannedEvent.InputTuple,
    BulkBannedEvent.OutputTuple,
    BulkBannedEvent.OutputObject
  >;
  getEvent(
    key: "FactorySet"
  ): TypedContractEvent<
    FactorySetEvent.InputTuple,
    FactorySetEvent.OutputTuple,
    FactorySetEvent.OutputObject
  >;
  getEvent(
    key: "ProjectApproved"
  ): TypedContractEvent<
    ProjectApprovedEvent.InputTuple,
    ProjectApprovedEvent.OutputTuple,
    ProjectApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectContractsRegistered"
  ): TypedContractEvent<
    ProjectContractsRegisteredEvent.InputTuple,
    ProjectContractsRegisteredEvent.OutputTuple,
    ProjectContractsRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProjectRevoked"
  ): TypedContractEvent<
    ProjectRevokedEvent.InputTuple,
    ProjectRevokedEvent.OutputTuple,
    ProjectRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TreasurySet"
  ): TypedContractEvent<
    TreasurySetEvent.InputTuple,
    TreasurySetEvent.OutputTuple,
    TreasurySetEvent.OutputObject
  >;

  filters: {
    "AddressBanned(address,address)": TypedContractEvent<
      AddressBannedEvent.InputTuple,
      AddressBannedEvent.OutputTuple,
      AddressBannedEvent.OutputObject
    >;
    AddressBanned: TypedContractEvent<
      AddressBannedEvent.InputTuple,
      AddressBannedEvent.OutputTuple,
      AddressBannedEvent.OutputObject
    >;

    "AddressUnbanned(address,address)": TypedContractEvent<
      AddressUnbannedEvent.InputTuple,
      AddressUnbannedEvent.OutputTuple,
      AddressUnbannedEvent.OutputObject
    >;
    AddressUnbanned: TypedContractEvent<
      AddressUnbannedEvent.InputTuple,
      AddressUnbannedEvent.OutputTuple,
      AddressUnbannedEvent.OutputObject
    >;

    "AdminTransferCompleted(address)": TypedContractEvent<
      AdminTransferCompletedEvent.InputTuple,
      AdminTransferCompletedEvent.OutputTuple,
      AdminTransferCompletedEvent.OutputObject
    >;
    AdminTransferCompleted: TypedContractEvent<
      AdminTransferCompletedEvent.InputTuple,
      AdminTransferCompletedEvent.OutputTuple,
      AdminTransferCompletedEvent.OutputObject
    >;

    "AdminTransferInitiated(address)": TypedContractEvent<
      AdminTransferInitiatedEvent.InputTuple,
      AdminTransferInitiatedEvent.OutputTuple,
      AdminTransferInitiatedEvent.OutputObject
    >;
    AdminTransferInitiated: TypedContractEvent<
      AdminTransferInitiatedEvent.InputTuple,
      AdminTransferInitiatedEvent.OutputTuple,
      AdminTransferInitiatedEvent.OutputObject
    >;

    "BanListSet(address)": TypedContractEvent<
      BanListSetEvent.InputTuple,
      BanListSetEvent.OutputTuple,
      BanListSetEvent.OutputObject
    >;
    BanListSet: TypedContractEvent<
      BanListSetEvent.InputTuple,
      BanListSetEvent.OutputTuple,
      BanListSetEvent.OutputObject
    >;

    "BulkBanned(uint256,address)": TypedContractEvent<
      BulkBannedEvent.InputTuple,
      BulkBannedEvent.OutputTuple,
      BulkBannedEvent.OutputObject
    >;
    BulkBanned: TypedContractEvent<
      BulkBannedEvent.InputTuple,
      BulkBannedEvent.OutputTuple,
      BulkBannedEvent.OutputObject
    >;

    "FactorySet(address)": TypedContractEvent<
      FactorySetEvent.InputTuple,
      FactorySetEvent.OutputTuple,
      FactorySetEvent.OutputObject
    >;
    FactorySet: TypedContractEvent<
      FactorySetEvent.InputTuple,
      FactorySetEvent.OutputTuple,
      FactorySetEvent.OutputObject
    >;

    "ProjectApproved(address,string)": TypedContractEvent<
      ProjectApprovedEvent.InputTuple,
      ProjectApprovedEvent.OutputTuple,
      ProjectApprovedEvent.OutputObject
    >;
    ProjectApproved: TypedContractEvent<
      ProjectApprovedEvent.InputTuple,
      ProjectApprovedEvent.OutputTuple,
      ProjectApprovedEvent.OutputObject
    >;

    "ProjectContractsRegistered(address)": TypedContractEvent<
      ProjectContractsRegisteredEvent.InputTuple,
      ProjectContractsRegisteredEvent.OutputTuple,
      ProjectContractsRegisteredEvent.OutputObject
    >;
    ProjectContractsRegistered: TypedContractEvent<
      ProjectContractsRegisteredEvent.InputTuple,
      ProjectContractsRegisteredEvent.OutputTuple,
      ProjectContractsRegisteredEvent.OutputObject
    >;

    "ProjectRevoked(address)": TypedContractEvent<
      ProjectRevokedEvent.InputTuple,
      ProjectRevokedEvent.OutputTuple,
      ProjectRevokedEvent.OutputObject
    >;
    ProjectRevoked: TypedContractEvent<
      ProjectRevokedEvent.InputTuple,
      ProjectRevokedEvent.OutputTuple,
      ProjectRevokedEvent.OutputObject
    >;

    "TreasurySet(address)": TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;
    TreasurySet: TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;
  };
}
