/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRWAToken__factory } from "./IRWAToken__factory";
export { IRegistry__factory } from "./IRegistry__factory";
