/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBurnReserveSetPrice,
  IBurnReserveSetPriceInterface,
} from "../../../../contracts/project/TokenSale.sol/IBurnReserveSetPrice";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "setIcoPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBurnReserveSetPrice__factory {
  static readonly abi = _abi;
  static createInterface(): IBurnReserveSetPriceInterface {
    return new Interface(_abi) as IBurnReserveSetPriceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBurnReserveSetPrice {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBurnReserveSetPrice;
  }
}
