/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProtocolTreasuryReceive,
  IProtocolTreasuryReceiveInterface,
} from "../../../../contracts/project/TokenSale.sol/IProtocolTreasuryReceive";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "receiveFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IProtocolTreasuryReceive__factory {
  static readonly abi = _abi;
  static createInterface(): IProtocolTreasuryReceiveInterface {
    return new Interface(_abi) as IProtocolTreasuryReceiveInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProtocolTreasuryReceive {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IProtocolTreasuryReceive;
  }
}
