/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as burnReserveSol from "./BurnReserve.sol";
export type { burnReserveSol };
import type * as revenueRouterSol from "./RevenueRouter.sol";
export type { revenueRouterSol };
import type * as tokenSaleSol from "./TokenSale.sol";
export type { tokenSaleSol };
export type { RWAToken } from "./RWAToken";
export type { StakingPool } from "./StakingPool";
