/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace StakingPool {
  export type EpochStruct = {
    snapshotId: BigNumberish;
    totalStakedAtSnapshot: BigNumberish;
    usdcEmission: BigNumberish;
    timestamp: BigNumberish;
  };

  export type EpochStructOutput = [
    snapshotId: bigint,
    totalStakedAtSnapshot: bigint,
    usdcEmission: bigint,
    timestamp: bigint
  ] & {
    snapshotId: bigint;
    totalStakedAtSnapshot: bigint;
    usdcEmission: bigint;
    timestamp: bigint;
  };
}

export interface StakingPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EPOCH_DURATION"
      | "claimEmission"
      | "claimMultipleEpochs"
      | "claimed"
      | "currentEpoch"
      | "depositEmission"
      | "epochs"
      | "getEpoch"
      | "lastSnapshotTime"
      | "operator"
      | "pendingEmission"
      | "registry"
      | "stake"
      | "stakedBalance"
      | "stakerInfo"
      | "takeWeeklySnapshot"
      | "timeUntilNextSnapshot"
      | "token"
      | "totalStaked"
      | "unstake"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmissionClaimed"
      | "EmissionDeposited"
      | "EpochSnapshotTaken"
      | "Staked"
      | "Unstaked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EPOCH_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimEmission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimMultipleEpochs",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositEmission",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEpoch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastSnapshotTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingEmission",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "stakedBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakerInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "takeWeeklySnapshot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timeUntilNextSnapshot",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "EPOCH_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimEmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimMultipleEpochs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositEmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "epochs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEpoch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastSnapshotTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingEmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakerInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "takeWeeklySnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeUntilNextSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace EmissionClaimedEvent {
  export type InputTuple = [
    staker: AddressLike,
    epochId: BigNumberish,
    usdcAmount: BigNumberish
  ];
  export type OutputTuple = [
    staker: string,
    epochId: bigint,
    usdcAmount: bigint
  ];
  export interface OutputObject {
    staker: string;
    epochId: bigint;
    usdcAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmissionDepositedEvent {
  export type InputTuple = [epochId: BigNumberish, usdcAmount: BigNumberish];
  export type OutputTuple = [epochId: bigint, usdcAmount: bigint];
  export interface OutputObject {
    epochId: bigint;
    usdcAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EpochSnapshotTakenEvent {
  export type InputTuple = [
    epochId: BigNumberish,
    snapshotId: BigNumberish,
    totalStaked: BigNumberish
  ];
  export type OutputTuple = [
    epochId: bigint,
    snapshotId: bigint,
    totalStaked: bigint
  ];
  export interface OutputObject {
    epochId: bigint;
    snapshotId: bigint;
    totalStaked: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [staker: AddressLike, amount: BigNumberish];
  export type OutputTuple = [staker: string, amount: bigint];
  export interface OutputObject {
    staker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [staker: AddressLike, amount: BigNumberish];
  export type OutputTuple = [staker: string, amount: bigint];
  export interface OutputObject {
    staker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StakingPool extends BaseContract {
  connect(runner?: ContractRunner | null): StakingPool;
  waitForDeployment(): Promise<this>;

  interface: StakingPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EPOCH_DURATION: TypedContractMethod<[], [bigint], "view">;

  claimEmission: TypedContractMethod<
    [epochId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimMultipleEpochs: TypedContractMethod<
    [epochIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  claimed: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  currentEpoch: TypedContractMethod<[], [bigint], "view">;

  depositEmission: TypedContractMethod<
    [epochId: BigNumberish, usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  epochs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        snapshotId: bigint;
        totalStakedAtSnapshot: bigint;
        usdcEmission: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEpoch: TypedContractMethod<
    [epochId: BigNumberish],
    [StakingPool.EpochStructOutput],
    "view"
  >;

  lastSnapshotTime: TypedContractMethod<[], [bigint], "view">;

  operator: TypedContractMethod<[], [string], "view">;

  pendingEmission: TypedContractMethod<
    [staker: AddressLike, epochId: BigNumberish],
    [bigint],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  stake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  stakedBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  stakerInfo: TypedContractMethod<
    [staker: AddressLike],
    [[bigint, bigint] & { staked: bigint; checkpointCount: bigint }],
    "view"
  >;

  takeWeeklySnapshot: TypedContractMethod<[], [bigint], "nonpayable">;

  timeUntilNextSnapshot: TypedContractMethod<[], [bigint], "view">;

  token: TypedContractMethod<[], [string], "view">;

  totalStaked: TypedContractMethod<[], [bigint], "view">;

  unstake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EPOCH_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimEmission"
  ): TypedContractMethod<[epochId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimMultipleEpochs"
  ): TypedContractMethod<[epochIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimed"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "currentEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositEmission"
  ): TypedContractMethod<
    [epochId: BigNumberish, usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "epochs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        snapshotId: bigint;
        totalStakedAtSnapshot: bigint;
        usdcEmission: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEpoch"
  ): TypedContractMethod<
    [epochId: BigNumberish],
    [StakingPool.EpochStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastSnapshotTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingEmission"
  ): TypedContractMethod<
    [staker: AddressLike, epochId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakedBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakerInfo"
  ): TypedContractMethod<
    [staker: AddressLike],
    [[bigint, bigint] & { staked: bigint; checkpointCount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "takeWeeklySnapshot"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "timeUntilNextSnapshot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EmissionClaimed"
  ): TypedContractEvent<
    EmissionClaimedEvent.InputTuple,
    EmissionClaimedEvent.OutputTuple,
    EmissionClaimedEvent.OutputObject
  >;
  getEvent(
    key: "EmissionDeposited"
  ): TypedContractEvent<
    EmissionDepositedEvent.InputTuple,
    EmissionDepositedEvent.OutputTuple,
    EmissionDepositedEvent.OutputObject
  >;
  getEvent(
    key: "EpochSnapshotTaken"
  ): TypedContractEvent<
    EpochSnapshotTakenEvent.InputTuple,
    EpochSnapshotTakenEvent.OutputTuple,
    EpochSnapshotTakenEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;

  filters: {
    "EmissionClaimed(address,uint256,uint256)": TypedContractEvent<
      EmissionClaimedEvent.InputTuple,
      EmissionClaimedEvent.OutputTuple,
      EmissionClaimedEvent.OutputObject
    >;
    EmissionClaimed: TypedContractEvent<
      EmissionClaimedEvent.InputTuple,
      EmissionClaimedEvent.OutputTuple,
      EmissionClaimedEvent.OutputObject
    >;

    "EmissionDeposited(uint256,uint256)": TypedContractEvent<
      EmissionDepositedEvent.InputTuple,
      EmissionDepositedEvent.OutputTuple,
      EmissionDepositedEvent.OutputObject
    >;
    EmissionDeposited: TypedContractEvent<
      EmissionDepositedEvent.InputTuple,
      EmissionDepositedEvent.OutputTuple,
      EmissionDepositedEvent.OutputObject
    >;

    "EpochSnapshotTaken(uint256,uint256,uint256)": TypedContractEvent<
      EpochSnapshotTakenEvent.InputTuple,
      EpochSnapshotTakenEvent.OutputTuple,
      EpochSnapshotTakenEvent.OutputObject
    >;
    EpochSnapshotTaken: TypedContractEvent<
      EpochSnapshotTakenEvent.InputTuple,
      EpochSnapshotTakenEvent.OutputTuple,
      EpochSnapshotTakenEvent.OutputObject
    >;

    "Staked(address,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unstaked(address,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
  };
}
