/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBurnReserveSetPrice } from "./IBurnReserveSetPrice";
export type { IProtocolTreasuryReceive } from "./IProtocolTreasuryReceive";
export type { IRWATokenSale } from "./IRWATokenSale";
export type { TokenSale } from "./TokenSale";
